In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import tree

In [2]:
from sqlalchemy import create_engine
from hold import connection_string

In [3]:
engine = create_engine(f'{connection_string}', encoding='iso-8859-1', connect_args={'connect_timeout': 10})

In [4]:
gtdDF = pd.read_sql_table('global_terrorism', con= engine)

In [5]:
casualties = gtdDF['nkill'] + gtdDF['nwound']
casualties.sum()

554384.0

In [6]:
gtdDF['casualties'] = gtdDF['nkill'] + gtdDF['nwound']
gtdDF.head()

,iyear,imonth,iday,date,country_txt,region_txt,provstate,city,latitude,longitude,...,weaptype1_txt,weapsubtype1_txt,weaptype2_txt,weapsubtype2_txt,kidhijcountry,ransom,nkill,nwound,index1,casualties
0,2000,1,1,2000-01-01,Namibia,Sub-Saharan Africa,Kavango,Muitjiku,-17.91,19.99,...,Firearms,Unknown Gun Type,None,None,None,NaN,0.0,7.0,1.0,7.0
1,2000,1,1,2000-01-01,Namibia,Sub-Saharan Africa,Kavango,Muitjiku,-17.91,19.99,...,Firearms,Unknown Gun Type,None,None,None,0.0,0.0,7.0,2.0,7.0
2,2000,1,1,2000-01-01,India,South Asia,Jammu and Kashmir,Udhampur,32.93,75.14,...,Firearms,Unknown Gun Type,None,None,None,NaN,1.0,2.0,3.0,3.0
3,2000,1,1,2000-01-01,Kosovo,Eastern Europe,Kosovo (Province),Peje,42.66,20.31,...,Explosives/Bombs/Dynamite,Unknown Explosive Type,None,None,None,NaN,0.0,1.0,4.0,1.0
4,2000,1,1,2000-01-01,Somalia,Sub-Saharan Africa,Banaadir,Mogadishu,2.11,45.39,...,Firearms,Unknown Gun Type,None,None,None,NaN,6.0,10.0,5.0,16.0

In [7]:
CountryCasualtiesDF = gtdDF[['index1','country_txt','casualties']]
CountryCasualtiesDF.head()

   index1 country_txt  casualties
0     1.0     Namibia         7.0
1     2.0     Namibia         7.0
2     3.0       India         3.0
3     4.0      Kosovo         1.0
4     5.0     Somalia        16.0

In [8]:
CountryCasualties2DF = pd.get_dummies(CountryCasualtiesDF)
CountryCasualties2DF.head()

,index1,casualties,country_txt_Afghanistan,country_txt_Albania,country_txt_Algeria,country_txt_Angola,country_txt_Argentina,country_txt_Armenia,country_txt_Australia,country_txt_Austria,...,country_txt_Uruguay,country_txt_Uzbekistan,country_txt_Venezuela,country_txt_Vietnam,country_txt_West Bank and Gaza Strip,country_txt_Western Sahara,country_txt_Yemen,country_txt_Yugoslavia,country_txt_Zambia,country_txt_Zimbabwe
0,1.0,7.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2.0,7.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3.0,3.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4.0,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5.0,16.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
CountryCasualtiesMergeDF = result = pd.merge(CountryCasualties2DF,CountryCasualtiesDF[['index1','country_txt']],on='index1')
#RegionCasualtiesMergeDF
CountryCasualtiesMergeDF.head()

,index1,casualties,country_txt_Afghanistan,country_txt_Albania,country_txt_Algeria,country_txt_Angola,country_txt_Argentina,country_txt_Armenia,country_txt_Australia,country_txt_Austria,...,country_txt_Uzbekistan,country_txt_Venezuela,country_txt_Vietnam,country_txt_West Bank and Gaza Strip,country_txt_Western Sahara,country_txt_Yemen,country_txt_Yugoslavia,country_txt_Zambia,country_txt_Zimbabwe,country_txt
0,1.0,7.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Namibia
1,2.0,7.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Namibia
2,3.0,3.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,India
3,4.0,1.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Kosovo
4,5.0,16.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Somalia

In [12]:
# Assign X (data) and y (target)
data = CountryCasualtiesMergeDF.drop(["index1","casualties","country_txt"], axis=1)
target = CountryCasualtiesMergeDF["country_txt"]
feature_names = data.columns

print(data.shape, target.shape)

(92700, 164) (92700,)

In [13]:
# Split the data into training and testing
### BEGIN SOLUTION
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)
### END SOLUTION

In [14]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.9996548004314995

In [15]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9996548004314995

In [16]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.16910401373783454, 'country_txt_Iraq'),
 (0.11137805936295672, 'country_txt_Pakistan'),
 (0.10747575602433024, 'country_txt_Afghanistan'),
 (0.08127483568379629, 'country_txt_India'),
 (0.04780995776845069, 'country_txt_Philippines'),
 (0.040802281336650974, 'country_txt_Thailand'),
 (0.03123179676016717, 'country_txt_Yemen'),
 (0.03080292410124834, 'country_txt_Somalia'),
 (0.029460173747668503, 'country_txt_Nigeria'),
 (0.022975232241238125, 'country_txt_Colombia'),
 (0.02280174184149403, 'country_txt_Russia'),
 (0.022163313884033257, 'country_txt_Libya'),
 (0.020757357935294905, 'country_txt_Egypt'),
 (0.01930692119269324, 'country_txt_Turkey'),
 (0.018314484413169834, 'country_txt_Ukraine'),
 (0.01603692614597709, 'country_txt_Syria'),
 (0.015625058627695178, 'country_txt_Algeria'),
 (0.015022909847770103, 'country_txt_West Bank and Gaza Strip'),
 (0.013555833137848758, 'country_txt_Israel'),
 (0.012385075930153628, 'country_txt_Bangladesh'),
 (0.011784330573573691, 'country_txt_United Kingdom'),
 (0.011077066167202745, 'country_txt_Nepal'),
 (0.00932792542408834, 'country_txt_Sri Lanka'),
 (0.007353503916075831, 'country_txt_Lebanon'),
 (0.007022090157616696, 'country_txt_Sudan'),
 (0.006473984344911083, 'country_txt_Indonesia'),
 (0.006240241302460357, 'country_txt_Greece'),
 (0.006088625909091927, 'country_txt_Democratic Republic of the Congo'),
 (0.005881520977945982, 'country_txt_Kenya'),
 (0.005395123646296241, 'country_txt_Spain'),
 (0.0051550150507751556, 'country_txt_United States'),
 (0.005109565702703407, 'country_txt_France'),
 (0.004173063770870157, 'country_txt_Mali'),
 (0.0041229773461278945, 'country_txt_Burundi'),
 (0.0031634298015214076, 'country_txt_Saudi Arabia'),
 (0.002544620033498835, 'country_txt_Myanmar'),
 (0.0022244856197282652, 'country_txt_Germany'),
 (0.0021417096193093775, 'country_txt_Central African Republic'),
 (0.002106716940724658, 'country_txt_Cameroon'),
 (0.0019282395459818526, 'country_txt_Kosovo'),
 (0.0019155379337472858, 'country_txt_Ireland'),
 (0.001860007131742951, 'country_txt_Bahrain'),
 (0.0017341531670470923, 'country_txt_Uganda'),
 (0.0017029533470407812, 'country_txt_Iran'),
 (0.001667371683244758, 'country_txt_Mozambique'),
 (0.0015704692378160506, 'country_txt_China'),
 (0.0014910346712402997, 'country_txt_South Sudan'),
 (0.0013947810903391883, 'country_txt_South Africa'),
 (0.0013542050147041349, 'country_txt_Macedonia'),
 (0.0013342177969337358, 'country_txt_Georgia'),
 (0.0013314213547380514, 'country_txt_Italy'),
 (0.0011123488445728734, 'country_txt_Mexico'),
 (0.0010521052964899097, 'country_txt_Niger'),
 (0.000998888137572397, 'country_txt_Tunisia'),
 (0.0009586011166773023, 'country_txt_Chile'),
 (0.0009278318615796273, 'country_txt_Sweden'),
 (0.0008176566943483269, 'country_txt_Ethiopia'),
 (0.0007652943648272909, 'country_txt_Peru'),
 (0.0007642292070999209, 'country_txt_Angola'),
 (0.0007318000001950342, 'country_txt_Malaysia'),
 (0.0007311455485261952, 'country_txt_Paraguay'),
 (0.0005994492662791693, 'country_txt_Chad'),
 (0.0005758106510312843, 'country_txt_Australia'),
 (0.0005740250249091702, 'country_txt_Canada'),
 (0.0005624675670051228, 'country_txt_Japan'),
 (0.0005307512441473939, 'country_txt_Tanzania'),
 (0.00048772613594683323, 'country_txt_Senegal'),
 (0.00048156151210091244, 'country_txt_Ivory Coast'),
 (0.00044939879164224947, 'country_txt_Yugoslavia'),
 (0.00041316053768977387, 'country_txt_Bosnia-Herzegovina'),
 (0.00040575818008397273, 'country_txt_Jordan'),
 (0.0003820274254259741, 'country_txt_Venezuela'),
 (0.0003560801520988924, 'country_txt_Ecuador'),
 (0.00033631080341732213, 'country_txt_Cyprus'),
 (0.0003230434387205901, 'country_txt_Kyrgyzstan'),
 (0.00032204641262524353, 'country_txt_Tajikistan'),
 (0.0003215201586470249, 'country_txt_Namibia'),
 (0.0003185996434704838, 'country_txt_Belgium'),
 (0.0003169131310186436, 'country_txt_Rwanda'),
 (0.0003036777913643306, 'country_txt_Netherlands'),
 (0.0002839488366057491, 'country_txt_Kazakhstan'),
 (0.0002818539044643279, 'country_txt_Zimbabwe'),
 (0.0002795504442960967, 'country_txt_Haiti'),
 (0.00026598837215567616, 'country_txt_Cambodia'),
 (0.00024574825502936796, 'country_txt_Austria'),
 (0.00023600376653793074, 'country_txt_Guatemala'),
 (0.00023335152451102052, 'country_txt_Bulgaria'),
 (0.0002181121136419709, 'country_txt_Albania'),
 (0.00021531635313024326, 'country_txt_Argentina'),
 (0.0002146831449410707, 'country_txt_Maldives'),
 (0.00021013775968885276, 'country_txt_Brazil'),
 (0.00020837336250682028, 'country_txt_Czech Republic'),
 (0.0002002784842408994, 'country_txt_Honduras'),
 (0.00018078289639477266, 'country_txt_Sierra Leone'),
 (0.00017122108668566848, 'country_txt_Azerbaijan'),
 (0.00017089393924649295, 'country_txt_Burkina Faso'),
 (0.00016533083905592136, 'country_txt_New Zealand'),
 (0.00016198734327808867, 'country_txt_Laos'),
 (0.00016196231082728763, 'country_txt_Serbia'),
 (0.0001605057900304444, 'country_txt_Switzerland'),
 (0.00014958865254758626, 'country_txt_Finland'),
 (0.0001467551632835077, 'country_txt_Serbia-Montenegro'),
 (0.00014467288300604316, 'country_txt_Mauritania'),
 (0.00013874475990644075, 'country_txt_Morocco'),
 (0.00013826832937540606, 'country_txt_Armenia'),
 (0.0001335162048860085, 'country_txt_Guyana'),
 (0.0001325853659807727, 'country_txt_Croatia'),
 (0.00013096266516802484, 'country_txt_Madagascar'),
 (0.0001280038341290463, 'country_txt_Zambia'),
 (0.00011691200434176392, 'country_txt_Bolivia'),
 (0.0001148915196187952, 'country_txt_Guinea'),
 (0.00011231566667898549, 'country_txt_Hungary'),
 (0.00011097413185832408, 'country_txt_Taiwan'),
 (0.00010703164879045539, 'country_txt_Uzbekistan'),
 (9.947420256329947e-05, 'country_txt_Denmark'),
 (9.942163330189835e-05, 'country_txt_Guinea-Bissau'),
 (9.500853597484882e-05, 'country_txt_Norway'),
 (8.538867211066858e-05, 'country_txt_East Timor'),
 (8.151245675920216e-05, 'country_txt_Swaziland'),
 (8.095430522355937e-05, 'country_txt_Republic of the Congo'),
 (8.081511033354019e-05, 'country_txt_Montenegro'),
 (7.990696177624713e-05, 'country_txt_Trinidad and Tobago'),
 (7.962548508560725e-05, 'country_txt_United Arab Emirates'),
 (7.891416139245834e-05, 'country_txt_Kuwait'),
 (7.058097349045145e-05, 'country_txt_Bhutan'),
 (6.484609851697704e-05, 'country_txt_Belarus'),
 (6.479815350528465e-05, 'country_txt_Latvia'),
 (6.457603781314033e-05, 'country_txt_Liberia'),
 (6.432696826628201e-05, 'country_txt_Vietnam'),
 (6.403842743775155e-05, 'country_txt_South Korea'),
 (4.863399722095391e-05, 'country_txt_Eritrea'),
 (4.7941661854992653e-05, 'country_txt_Estonia'),
 (4.782972101113934e-05, 'country_txt_Panama'),
 (4.747472346178523e-05, 'country_txt_Hong Kong'),
 (4.656782822056848e-05, 'country_txt_Moldova'),
 (4.6412051577956386e-05, 'country_txt_Nicaragua'),
 (3.348557085212259e-05, 'country_txt_Malta'),
 (3.245056522525596e-05, 'country_txt_Djibouti'),
 (3.23524292386e-05, 'country_txt_Slovak Republic'),
 (3.193147973443423e-05, 'country_txt_Qatar'),
 (3.176578718443204e-05, 'country_txt_Turkmenistan'),
 (3.142602579618188e-05, 'country_txt_Dominican Republic'),
 (3.1320374501475795e-05, 'country_txt_Solomon Islands'),
 (3.1286345369325964e-05, 'country_txt_Fiji'),
 (3.103851952027086e-05, 'country_txt_Uruguay'),
 (3.078815831428887e-05, 'country_txt_Portugal'),
 (3.048556891920346e-05, 'country_txt_Belize'),
 (1.8403289372224438e-05, 'country_txt_Poland'),
 (1.804081803801488e-05, 'country_txt_Gambia'),
 (1.7391003687030458e-05, 'country_txt_Jamaica'),
 (1.6799773138868288e-05, 'country_txt_St. Lucia'),
 (1.6721367035523378e-05, 'country_txt_Equatorial Guinea'),
 (1.6530894537171922e-05, 'country_txt_Ghana'),
 (1.590178895347234e-05, 'country_txt_Malawi'),
 (1.5541282377157073e-05, 'country_txt_Cuba'),
 (1.538901276800488e-05, 'country_txt_Bahamas'),
 (1.5377482615420763e-05, 'country_txt_Lesotho'),
 (0.0, 'country_txt_Western Sahara'),
 (0.0, 'country_txt_Togo'),
 (0.0, 'country_txt_Slovenia'),
 (0.0, 'country_txt_Romania'),
 (0.0, 'country_txt_International'),
 (0.0, 'country_txt_Iceland'),
 (0.0, 'country_txt_Costa Rica')]